<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aeroland_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="shivali@todo.todo">shivali</maintainer>
  <license>Apache-2.0</license>

  <depend>aeroland_navigation</depend>
  <depend>turtlesim</depend>
  <depend>aeroland_core</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ros_gz_image</exec_depend>
  <exec_depend>aeroland_perception</exec_depend>
  <exec_depend>aeroland_landing</exec_depend>
  <exec_depend>aeroland_analysis</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
